---
## Code Book: Describes the variables used in the run_analysis.R file
---

# Variables:
  Subject: is the subject ID - integer - there are 30 subjects in this data set.
  Activity: name of activity teh the subjects participated in- string - there are 6 activities:
        - WALKING, 
        - WALKING_UPSTAIRS
        - WALKING_DOWNSTAIRS
        - SITTING
        - STANDING
        - LAYING
  
  All other variables are either the mean or standard deviation (this is indicated in the name of the variable) of a specific measurmnet for each subject on each activity.
  The measurments include: 
  
 - Time domain body acceleration mean along X, Y, and Z
 - Time domain body acceleration standard deviation along X, Y, and Z
 - Time domain gravity acceleration mean along X, Y, and Z
 - Time domain gravity acceleration standard deviation along X, Y, and Z  
 - Time domain body jerk mean along X, Y, and Z   
 - Time domain body jerk standard deviation along X, Y, and Z
 - Time domain gyroscope mean along X, Y, and Z
 - Time domain gyroscope standard deviation along X, Y, and Z
 - Time domain gyroscope jerk mean along X, Y, and Z
 - Time domain gyroscope jerk standard deviation along X, Y, and Z
 - Time domain body acceleration magnitude mean
 - Time domain body acceleration magnitude standard deviation
 - Time domain gravity acceleration magnitude mean
 - Time domain gravity acceleration magnitude standard deviation
 - Time domain body jerk magnitude mean
 - Time domain body jerk magnitude standard deviation
 - Time domain gyroscope magnitude mean
 - Time domain gyroscope magnitude standard deviation
 - Time domain gyroscope jerk magnitude mean
 - Time domain gyroscope jerk magnitude standard deviation
 - Frequency domain body acceleration mean along X, Y, and Z
 - Frequency domain body acceleration standard deviation along X, Y, and Z
 - Frequency domain body jerk mean along X, Y, and Z
 - Frequency domain body jerk standard deviation along X, Y, and Z
 - Frequency domain gyroscope mean along X, Y, and Z
 - Frequency domain gyroscope standard deviation along X, Y, and Z
 - Frequency domain body acceleration magnitude mean
 - Frequency domain body acceleration magnitude standard deviation
 - Frequency domain body jerk magnitude mean
 - Frequency domain body jerk magnitude standard deviation
 - Frequency domain gyroscope magnitude mean
 - Frequency domain gyroscope magnitude standard deviation
 - Frequency domain gyroscope jerk magnitude mean
 - Frequency domain gyroscope jerk magnitude standard deviation
